<div ng-controller='StudentCoursesController' style='min-height: 95%'>

    <div class="row main-row" ng-controller='MessageCtrl' style='width: 1024px'>
        <div class="col-sm-12">
            <div style='display: none' class="alert alert-success" role="alert"><b>New!</b> You can now use Messages to communicate with advisors and submit clarifications.</div>
            
            <div class="panel panel-default">
                <table id='student-courses-table' class='table table-hover'>
                    <thead>
                        <tr>
                            <th style='width: 1px'>#</th>
                            <th>Course name</th>
                            <th style='width: 1px'>Units</th>
                            <th style='width: 1px'>Description</th>
                            <th style='width: 1px'>Type</th>
                            <th style='width: 1px'>Date</th>
                            <th style='width: 100px'>Status</th>
                            <th style='width: 1px'>Messages</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-if="false" ng-repeat-start="course in courses"></tr>
                        
                        <tr ng-if="!course.large_row_type">
                            <th scope="row">{{ course.id + 1 }}</th>
                            <td>{{ generateCourseNameNumberText(course) }}</td>
                            <td>{{ course.taking_as == 'place-out' ? '-' : course.units }}</td>
                            
                            <td>
                                <a ng-show="course.course_description != ''" href='javascript: ;'
                                   ng-click="toggleCourseDescription($index, course)">
                                    {{ courseDescriptionShown[course.id] ? "Hide" : "Show" }}
                                </a>
                                <span ng-show="course.course_description == ''">-</span>
                            </td>
                            <td>{{ ucfirst(course.taking_as) }}</td>
                            
                            <td>{{ course.taking_as == 'place-out' ? '-' : generateDateText(course.submission_time) }}</td>
                            
                            <td>
                                <span ng-show="course.status == 'taking'">In progress</span>
                                <span ng-show="course.status == 'taken'" class='text-success'>Taken</span>
                                <span ng-show="course.status == 'submitted'" class='text-info'>Submitted, under review</span>
                                <span ng-show="course.status == 'rejected'" class='text-danger'>Rejected</span>
                                <span ng-show="course.status == 'approved'" class='text-success'>Approved</span>
                                <span ng-show="course.status == 'need-clarification'" class='text-warning'>Clarification needed</span>
                                <span ng-show="course.status == 'satisfied'" class='text-success'>Satisfied</span>
                                <span ng-show="course.status == 'not-satisfied'" class='text-danger'>Not satisfied</span>
                            </td>
                            
                            <td><a class='view-msg {{ course.has_unread_msg ? "text-danger" : "" }}'
                                ng-click='showMessages(course.id)'
                                href='javascript: ;'>
                                {{ course.has_unread_msg ? "Unread messages" : "View" }}
                            </a></td>
                        </tr>
                        
                        <tr ng-if="course.large_row_type" style='background-color: #f9f9f9'>
                            <td colspan="9" ng-if="course.large_row_type == 'description'" style='padding-left: 40px'>
                                <span style="font-weight: bold">Description:&nbsp</span>
                                {{ course.course_description }}
                            </td>
                            
                            <td colspan="9" ng-if="course.large_row_type == 'comment'" style='padding-left: 40px'>
                                <span style='font-weight: bold'>Advisor comment:&nbsp</span>
                                {{ course.comment }}
                            </td>
                        </tr>
                        
                        <tr ng-if="false" ng-repeat-end></tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
    <?php require_once(APPLICATION_PATH . "/../application/views/scripts/commons/messages.phtml"); ?>

</div>