<div ng-controller='StudentCoursesController' class='easy-page-body'>

    <div class="row main-row" ng-controller='MessageCtrl' style='width: 1024px'>
        <div class="col-sm-12">
            <div style='display: none' class="alert alert-success" role="alert"><b>New!</b> You can now use Messages to communicate with advisors and submit clarifications.</div>
            
            <div class="panel panel-default">
                <table id='student-courses-table' class='table table-hover'>
                    <thead>
                        <tr>
                            <th style='width: 1px' class='center-text'>#</th>
                            <th>Course name</th>
                            <th style='width: 1px' class='center-text'>Units</th>
                            <th style='width: 1px' class='center-text'>Description</th>
                            <th style='width: 1px' class='center-text'>Type</th>
                            <th style='width: 1px' class='center-text'>Date</th>
                            <th style='width: 100px' class='center-text'>Status</th>
                            <th style='width: 1px' class='center-text'>Messages</th>
                            <th style='max-width: 120px' class='center-text'>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-if="false" ng-repeat-start="course in courses"></tr>
                        
                        <tr ng-if="!course.large_row_type">
                            <th scope="row" class='center-text'>{{ course.display_id + 1 }}</th>
                            <td class='one-line'>{{ generateCourseNameNumberText(course) }}</td>
                            <td class='center-text'>{{ (course.taking_as == 'place-out' || course.units == 0) ? '-' : course.units }}</td>

                            <td class='center-text'>
                                <a ng-show="!(course.course_description == '' || course.course_description == null)" href='javascript: ;'
                                   ng-click="toggleCourseDescription($index, course)">
                                    {{ courseDescriptionShown[course.display_id] ? "Hide" : "Show" }}
                                </a>
                                <span ng-show="(course.course_description == '' || course.course_description == null)">-</span>
                            </td>
                            <td class='center-text'>{{ ucfirst(course.taking_as) }}</td>
                            
                            <td>{{ course.taking_as == 'place-out' ? '-' : generateDateText(course.submission_time) }}</td>
                            
                            <td class='one-line center-text'>
                                <span ng-show="course.status == 'taking'">In progress</span>
                                <span ng-show="course.status == 'taken'" class='text-success'>Taken</span>
                                <span ng-show="course.status == 'submitted'" class='text-info'>Under review</span>
                                <span ng-show="course.status == 'rejected'" class='text-danger'>Rejected</span>
                                <span ng-show="course.status == 'approved'" class='text-success'>Approved</span>
                                <span ng-show="course.status == 'need-clarification'" class='text-warning'>Clarification needed</span>
                                <span ng-show="course.status == 'satisfied'" class='text-success'>Satisfied</span>
                                <span ng-show="course.status == 'not-satisfied'" class='text-danger'>Not satisfied</span>
                            </td>
                            
                            <td class='center-text'><a class='view-msg {{ course.has_unread_msg ? "text-danger" : "" }}'
                                ng-click='showMessages(course.id)'
                                href='javascript: ;'>
                                {{ course.has_unread_msg ? "Unread messages" : "View" }}
                            </a></td>
                            
                            <td class='center-text'>
                                <div ng-show='course.status == "submitted" || course.status == "need-clarification"'
                                    class="btn-group btn-group-xs" role="group">
                                    <button type="button" class="btn btn-default" ng-click='updateEditingCourse(course)'
                                        data-toggle="modal" data-target="#update-course-modal">Edit</button>
                                    <button type="button" class="btn btn-danger" ng-click='removeCourse(course)'>Remove</button>
                                </div>
                                <div ng-show='course.status != "submitted" && course.status != "need-clarification"'>-</div>
                             </td>
                        </tr>
                        
                        <tr ng-if="course.large_row_type" style='background-color: #f9f9f9'>
                            <td colspan="9" ng-if="course.large_row_type == 'description'" style='padding-left: 40px'>
                                <span style="font-weight: bold">Description:&nbsp</span>
                                {{ course.course_description }}
                            </td>
                            
                            <td colspan="9" ng-if="course.large_row_type == 'comment'" style='padding-left: 40px'>
                                <span style='font-weight: bold'>Advisor comment:&nbsp</span>
                                {{ course.comment }}
                            </td>
                        </tr>
                        
                        <tr ng-if="false" ng-repeat-end></tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
    <?php require_once(APPLICATION_PATH . "/../application/views/scripts/commons/messages.phtml"); ?>

    <div id='update-course-modal' class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Update Course Information</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Course number</label>
                            <div class="col-lg-9">
                                <label class="control-label" style='font-weight: normal'>{{ editingCourse.course_number }}</label>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Course name</label>
                            <div class="col-lg-9">
                                <label class="control-label" style='font-weight: normal'>{{ editingCourse.course_name }}</label>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Units</label>
                            <div class="col-lg-9">
                                <label class="control-label" style='font-weight: normal'>{{ editingCourse.units }}</label>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Type</label>
                            <div class="col-lg-9">
                                <label class="control-label" style='font-weight: normal'>{{ ucfirst(editingCourse.taking_as) }}</label>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Description</label>
                            <div class="col-lg-9">
                                <textarea ng-model='editingCourse.course_description' name='description' class="form-control" placeholder="Course description" rows='8'></textarea>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" data-dismiss='modal' ng-click='updateEditingCourseInfo()'>Save changes</button>
                </div>
            </div>
        </div>
    </div>
</div>