<div id='feedback' style='display:table; min-height:95%; width:100%; text-align:center'>
    <div style='display:table-cell; vertical-align:middle'>
        <div class="panel panel-default" style='width: 480px; margin-left: auto; margin-right: auto'>
            <div class="panel-heading bold" style='font-size: 17px; text-align: center'>Send Feedback and Complaints to the Developer</div>
            <div class="panel-body">
                <?php if ($this->submitted) { ?>
                <div class="alert alert-success" style='width: 400px; margin-left: auto; margin-right: auto'>Submitted. Thank you for your feedback!</div>
                <?php } ?>
                
                Found bugs? Think EASy is too ugly? Want some new features?
                <br />
                We need your feedback and want to hear more from you about<br />how we can improve EASy!
                
                <form action="" method="post">                    
                    <div class="input-group">
                        <textarea name='feedback' class="form-control" placeholder="Feedback" rows='12'></textarea>
                    </div>
                    
                    <div style='margin-top: 20px; margin-left: auto; margin-right: auto'>
                        <button id='submit-feedback' class='btn btn-primary' type="button" style='width: 150px'
                            onclick="$('form').submit()">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>