<div class="row main-row" style='height: 100%; width: 1024px'>
    <div id='div-student-info' class="col-sm-5" style='height: 100%'>
        <h3>My Info</h3>
        <table class='table'>
            <tr>
                <td style='width:200px'><b>Name</b></td>
                <td><?= $this->info->name ?></td>
            </tr>
            <tr>
                <td><b>Andrew ID</b></td>
                <td><?= $this->info->andrew_id ?></td>
            </tr>
            <tr>
                <td><b>Status</b></td>
                <td><?= ucfirst($this->info->status) ?></td>
            </tr>
            <tr>
                <td><b>FT/PT</b></td>
                <td><?php if ($this->info->is_full_time == '0') echo "Part Time"; else echo "Full Time"; ?></td>
            </tr>
            <tr>
                <td><b>Program</b></td>
                <td><?php if ($this->info->program == "ugminor") echo "Undergraduate Minor";
                          else if ($this->info->program == 'learning-media') echo 'Learning Media Minor';
                          else echo strtoupper($this->info->program); ?></td>
            </tr>
            <tr>
                <td><b>Entered Program</b></td>
                <td><?= $this->info->enroll_date ?></td>
            </tr>
            <tr>
                <td><b>Expected Graduation</b></td>
                <td><?= $this->info->graduation_date ?></td>
            </tr>
            <tr>
                <td><b>Primary Major</b></td>
                <td><?= $this->info->major ?></td>
            </tr>
        </table>
        
        Incorrect information? <a id='link-problem' href='javascript:;'>Request correction</a>.
        
        <div id='div-request-correction' style='margin-top:20px; display:none'>
            <textarea class='form-control' placeholder='Write your request to the advisor here'></textarea>
            <button style='margin-top:10px;float:right' class='btn btn-warning'>Request Correction</button>
        </div>
    </div>
    
    <div class='col-sm-7'>
        <h3>&nbsp;</h3>
        <h5>
            <span style='display: inline-block; margin-right: 20px'><span class='color-block progress-bar progress-bar-success'></span>Taken</span>
            <span style='display: inline-block;'><span class='color-block progress-bar progress-bar-info progress-bar-striped active'></span>In progress</span>
            <span class='pull-right' style='color: gray'>Hover for details</span>
        </h5>
        <h5>&nbsp;</h5>
        <h4>Core</h4>
        <div id='cores-progress' class="progress">
            <div id='cores-taken-bar' class="progress-bar progress-bar-success"></div>
            <div id='cores-taking-bar' class="progress-bar progress-bar-info progress-bar-striped active"></div>
            <div id='cores-left-bar' class='courses-remaining'></div>
        </div>

        <h5>&nbsp;</h5>
        <?php if ($this->info->program == 'bhci' || $this->info->program == 'ugminor') { ?>
            <h4>Prerequisites</h4>
            <div id='prerequisites-progress' class="progress">
                <div id='prerequisites-taken-bar' class="progress-bar progress-bar-success"></div>
                <div id='prerequisites-taking-bar' class="progress-bar progress-bar-info progress-bar-striped active"></div>
                <div id='prerequisites-left-bar' class='courses-remaining'></div>
            </div>
        <?php } else if ($this->info->program != "learning-media") { ?>
            <h4>Place-out</h4>
            <div id='placeouts-progress' class="progress">
                <div id='placeouts-taken-bar' class="progress-bar progress-bar-success"></div>
                <div id='placeouts-left-bar' class='courses-remaining'></div>
            </div>
        <?php } ?>

        <?php if ($this->electivesTotal > 0) { ?>
            <h5>&nbsp;</h5>
            <h4>Electives</h4>
            <div id='electives-progress' class="progress">
                <div id='electives-taken-bar' class="progress-bar progress-bar-success"></div>
                <div id='electives-taking-bar' class="progress-bar progress-bar-info progress-bar-striped active"></div>
                <div id='electives-left-bar' class='courses-remaining'></div>
            </div>
        <?php } ?>
        
        <?php if ($this->coursesSubmitted != 0) { ?>
            <h5>&nbsp;</h5>
            <h5 style='margin-top:40px'><label><?= $this->coursesSubmitted ?></label> submitted course<?= ($this->coursesSubmitted == 1 ? " is" : "s are") ?> currently under review.</h5>
        <?php } ?>

        <?php if ($this->clarificationNeeded != 0) { ?>
            <h5>&nbsp;</h5>
            <h5 style='margin-top:10px'><label><?= $this->clarificationNeeded ?></label> course<?= ($this->clarificationNeeded == 1 ? " needs" : "s need") ?> clarification.</h5>
        <?php } ?>

        <div id='data' style='display: none'>
            Cores total: <label id='cores-total'><?= $this->coresTotal ?></label>
            <br />
            Electives total: <label id='electives-total'><?= $this->electivesTotal ?></label>
            Electives taken: <label id='electives-taken'><?= $this->electivesTaken ?></label>
            Electives taking: <label id='electives-taking'><?= $this->electivesTaking ?></label>
            <br />
            <?php if ($this->bhciOrMinor) { ?>
            Prerequisites total: <label id='prerequisites-total'><?= $this->prerequisitesTotal ?></label>
            <?php } else if ($this->info->program != 'learning-media') { ?>
            Place-out total: <label id='placeouts-total'><?= $this->placeOutsTotal ?></label>
            Taken: <label id='placeouts-taken'><?= $this->placeOutsTaken ?></label>
            <?php } ?>

            <!-- Load all courses here since hard to compute on server side -->
            <!-- Load all but place-out and electives, since they don't require conflict-resolving -->
            <!-- All courses of this student -->
            All courses: <label id='courses-list'><?= $this->coursesList ?></label>
            Forced values: <label id='forced-values'><?= $this->forcedValues ?></label>

            Core requirements: <label id='cores-reqs'><?= $this->coresReqs ?></label>
            Core grade requirement: <label id='cores-grade-req'><?= $this->coresGradeReq ?></label>

            <?php if ($this->bhciOrMinor) { ?>
            Prerequisites requirements: <label id='prerequisites-reqs'><?= $this->prerequisitesReqs ?></label>
            Prerequisites grade requirement: <label id='prerequisites-grade-req'><?= $this->prerequisitesGradeReq ?></label>
            <?php } ?>

        </div>
    </div>
</div>