<div id='new-course' ng-controller='NewElectiveController' class='easy-page-body' style='display: table; width: 100%; text-align: center'>
    <div id='new-course-inner' style='display: table-cell; vertical-align: middle'>
        <div class="panel panel-default" style='width: 600px; margin-left: auto; margin-right: auto'>
            <div class="panel-heading bold" style='font-size: 17px; text-align: center'>Submit New Elective</div>
            <div class="panel-body">
                <?php if ($this->submission_error) { ?>
                <span class="alert alert-danger">Format error</span>
                <?php } ?>
                
                <?php if ($this->submitted) { ?>
                <div class="alert alert-success" style='width: 400px; margin-left: auto; margin-right: auto'>Course submitted successfully.<br />Course can be edited or removed on My Courses page.</div>
                <?php } ?>
                
                <form action="" method="post" class="form-horizontal" role="form">
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Course number</label>
                        <div class="col-lg-9">
                            <input type="text" ng-model='newElectiveNumber' name='course-number' class="form-control" placeholder="##-###">
                        </div>
                    </div>
                    
                    <div class='form-group' ng-show='isElectivePreapproved()'>
                        <label class="col-lg-3 control-label"></label>
                        <div class="col-lg-9">
                            <div style='margin: 0px; padding: 6px' class="alert alert-success" role="alert">
                                <span class='glyphicon glyphicon-ok-sign'></span>
                                This elective has been preapproved.
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Course name</label>
                        <div class="col-lg-9">
                            <input type="text" name='course-name' class="form-control">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Units</label>
                        <div class="col-lg-9">
                            <input type="number" name='units' class="form-control">
                        </div>
                    </div>

                    <?php if ($this->type == "mhci" || $this->type == 'metals') { ?>
                    <div class="form-group" id="course-type-selector">
                        <label class="col-lg-3 control-label">Type</label>
                        <span class="col-lg-9 btn-group" id='buttons-taking-as' data-toggle="buttons">
                            <label class="btn btn-default">
                                <input type="radio" name="taking-as" value="elective">Elective
                            </label>
                            <label class="btn btn-default">
                                <input type="radio" name="taking-as" value="place-out">Place-out
                            </label>
                        </span>
                    </div>
                    <?php } ?>
                    
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Description</label>
                        <div class="col-lg-9">
                            <textarea name='description' class="form-control" rows='8'></textarea>
                        </div>
                    </div>
                    
                    <div style='margin-top: 20px; margin-left: auto; margin-right: auto'>
                        <button id='submit-new-course' class='btn btn-primary' type="button" style='width: 150px'>Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>