<div id='login'>
    <div id='login-inner'>
        <div class="panel panel-default" style='margin-top: 20px'>
            <div class="panel-heading bold" style='font-size: 17px; text-align: center'>Reset Password</div>
            <div class="panel-body">
                <h5 style='width: 300px; margin-left: auto; margin-right: auto'>A reset email contains a temporary password which you can log in with to create a new password.</h5>
                <form action="" method="post">
                    <div class="form-input">
                        <input type="text" name='andrew-id' placeholder='Andrew ID' class="form-control">
                    </div>
                    <div style='width: 300px; margin-left: auto; margin-right: auto; margin-top: 20px'>
                        <button class='btn btn-warning' style='width: 300px' type="submit">Send Reset Email</button>
                    </div>
                </form>

                <h6 style='margin-top:50px'>*No email will be sent if this Andrew ID is not associated with any EASy account.</h6>
            </div>
        </div>
    </div>
</div>