<div class="panel panel-default" style='margin-top: 200px; width: 700px; margin-left: auto; margin-right: auto; font-size: 16px'>
    <div class="panel-body" style='text-align: center'>
        <h3>You are enrolled in multiple programs.</h3>
        <h4>Choose the one you want to view:</h4>

        <?php foreach ($this->users as $user) { ?>
        <h4>
            <a href='<?= $this->baseUrl(); ?>/users/select-program/program/<?= $user['program']; ?>'>
                <?php switch ($user['program']) {
                    case "bhci":
                        echo "BHCI";
                        break;
                    case "mhci":
                        echo "MHCI";
                        break;
                    case "learning-media":
                        echo "Learning Media Design";
                        break;
                    case "ugminor":
                        echo "Undergraduate Minor";
                        break;
                    case "metals":
                        echo "METALS";
                        break;
                    default:
                        echo $user['program'];
                } ?>
            </a>
        </h4>
        <?php } ?>
  </div>
</div>