    <div id="footer" style='height: 150px; background-color: #1b2940'>  
      <div id='footer-content' class='container' style='display: table; width: 90%; height: 100%'>
        <div id='footer-text' style='display: table-cell; vertical-align: middle; color: white; font-size: 14px'>
          <div>Human-Computer Interaction Institute</div>
          <div>School of Computer Science</div>
          <div>Carnegie Mellon University</div>
        </div>

        <div id='footer-image' style='display: table-cell; vertical-align: middle'>
          <img src="<?= $this->baseUrl(); ?>/public/images/cmu-logo.png" style='float: right'>
        </div>
      </div>
    </div>