<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--

Created by Chen Liu (CS'16) for Human-Computer Interaction Institute @ CMU
Hope you'll like it!

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="utf-8">
	<title><?=$this->title ?></title>
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/public/js/lib/jquery-2.0.3.min.js"></script>
    <link href="<?= $this->baseUrl(); ?>/public/css/lib/bootstrap.min.css" rel="stylesheet">
    <script src="<?= $this->baseUrl(); ?>/public/js/lib/bootstrap.min.js"></script>
	<?php
	$this->headLink()->prependStylesheet($this->baseUrl() . '/public/css/global.css');
	$this->headScript()->prependFile($this->baseUrl() . '/public/js/global.js');

	echo $this->headScript();
	echo $this->headLink();
	?>
</head>
<body>

    <?php echo $this->layout()->content; ?>

</body>
</html>