<div class="modal" id='modal-add-course' tabindex="-1" role="dialog" aria-labelledby="add-new-course" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Add Course</h4>
            </div>
            <div class="modal-body" style='padding-bottom: 0px'>
                <table class='table'>
                    <tr>
                        <td class='bold'>Course name</td>
                        <td>
                            <input class='form-control' ng-model='newCourse.name' />
                        </td>
                    </tr>
                    <tr>
                        <td class='bold'>Course number</td>
                        <td>
                            <input class='form-control' ng-model='newCourse.number' />
                        </td>
                    </tr>
                    <tr>
                        <td class='bold'>Units</td>
                        <td>
                            <input class='form-control' type='number' ng-model='newCourse.units' />
                        </td>
                    </tr>
                    <tr>
                        <td class='bold'>Taking as</td>
                        <td>
                            <span class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    {{ takingAs2Text[newCourse.takingAs] }}
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li ng-repeat='(k, v) in takingAsOptions'>
                                        <a href='#' ng-click='newCourse.takingAs = k'>{{ v }}</a>
                                    </li>
                                </ul>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td class='bold'>Status</td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    <span ng-show='newCourse.status == "need-clarification"' class='text-warning'>
                                        {{ status2Text[newCourse.status] }}
                                    </span>
                                    <span ng-show='newCourse.status == "submitted"' class='text-danger'>
                                        {{ status2Text[newCourse.status] }}
                                    </span>
                                    <span ng-show='newCourse.status == "approved"' class='text-success'>
                                        {{ status2Text[newCourse.status] }}
                                    </span>
                                    <span ng-show='newCourse.status != "need-clarification" && newCourse.status != "submitted" && newCourse.status != "approved"'>
                                        {{ status2Text[newCourse.status] }}
                                    </span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li ng-repeat='(k, v) in status2Text'>
                                        <a href='#' ng-click='newCourse.status = k'>{{ v }}</a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr ng-show='newCourse.status == "taken" || newCourse.status == "taking"'>
                        <td class='bold'>Semester</td>
                        <td>
                            <span class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    {{ newCourse.semester == null ? 'N/A' : newCourse.semester }}
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li ng-repeat='semesterOption in semesterOptions'>
                                        <a href='#' ng-click='newCourse.semester = semesterOption'>{{ semesterOption }}</a>
                                    </li>
                                </ul>
                            </span>
                            <span class="btn-group">
                                <input type='number' class='form-control' placeholder='Year' ng-model='newCourse.year'>
                            </span>
                        </td>
                    </tr>
                    <tr ng-show='newCourse.status == "taken"'>
                        <td class='bold'>Grade</td>
                        <td>
                            <span class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    {{ newCourse.grade == null ? 'N/A' : grade2Text[newCourse.grade] }}
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li ng-repeat='gradeOption in gradeOptions'>
                                        <a href='#' ng-click='newCourseGradeSelected(gradeOption)'>{{ gradeOption }}</a>
                                    </li>
                                </ul>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td class='bold'>Comment</td>
                        <td>
                            <textarea style='resize: vertical' class='form-control' rows='3' ng-model='newCourse.comment'></textarea>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" ng-click='addNewCourse()'>Add</button>
            </div>
        </div>
    </div>
</div>