<div ng-controller="PreapprovedElectivesController" class="row"
        style='width: 1000px; min-height: calc(100% - 55px); padding-bottom: 20px; margin-left: auto; margin-right: auto'>
    View preapproved electives for
    
    <div class="dropdown" style='display: inline-block'>
        <button class="btn btn-default dropdown-toggle" type="button" id="program-selector"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            BHCI <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="program-selector">
            <li><a href="#">BHCI</a></li>
        </ul>
    </div>
    
    <div class="panel panel-default" style='margin-top: 20px'>
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Course Number</th>
                    <th>Course Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>