<div ng-controller="PreapprovedElectivesController" class="row easy-page-body" style='width: 950px'>
    View preapproved electives for
    
    <div class="dropdown" style='display: inline-block'>
        <button class="btn btn-default dropdown-toggle" type="button" id="program-selector"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            {{ selectedProgram[1] }} <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="program-selector">
            <li ng-repeat="program in programs">
                <a role="menuitem" tabindex="-1" href="#" ng-click="programSelected(program)">{{ program[1] }}</a>
            </li>
        </ul>
    </div>
    
    <div class="panel panel-default" style='margin-top: 20px'>
        <table id='preapproved-electives-table' class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Course Number</th>
                    <th>Course Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="elective in electives">
                    <th scope="row" style='width: 1px'>{{ $index + 1 }}</th>
                    <td style='width: 180px'>{{ elective.course_number }}</td>
                    <td>{{ elective.course_name }}</td>
                    <td style='width: 200px'>
                        <button class="btn btn-danger btn-xs" ng-click="delete(elective)" type="button">Delete</button>
                        <!--<button class="btn btn-warning btn-xs" type="button">Edit</button>-->
                    </td>
                </tr>
                
                <tr ng-show="!electives.length">
                    <th style='width: 50px'></th>
                    <td style='width: 180px'><i>No courses found</i></td>
                    <td></td>
                    <td style='width: 200px'></td>
                </tr>
                
                <tr>
                    <th></th>
                    <td><input id="new-course-number-input" type="text" class="form-control" placeholder="Click to add a course"
                        ng-model="newCourseNumber" ng-click="enterNewCourseEditing()" ng-blur="exitNewCourseEditing()" ng-keypress="keyPressed($event)"></td>
                    <td><input id="new-course-name-input" ng-show="newCourseEditing" type="text" class="form-control"
                        ng-blur="exitNewCourseEditing()" placeholder="Course name" ng-model="newCourseName" ng-keypress="keyPressed($event)"></td>
                    <td>
                        <button ng-show="newCourseEditing" class="btn btn-success" ng-click="addNewCourse()"
                            data-toggle="popover" id='btn-add-new-course' type="button">Add</button>
                        <button ng-show="newCourseEditing" class="btn btn-default" ng-click="clearNewCourse()" type="button">Clear</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>