<div ng-controller="StatisticsController" class="row" style='width: 950px; min-height: calc(100% - 55px); padding-bottom: 20px; margin-left: auto; margin-right: auto'>
    <div class="col-sm-12" style='height: 100%'>
        View top <input id='count-input' class='form-control' style='width:60px; display:inline !important' ng-model="numElectivesToShow" /> approved elective requests from
        <span class="dropdown" style='display: inline-block'>
            <button class="btn btn-default dropdown-toggle" type="button" id="program-select" data-toggle="dropdown" aria-expanded="true">
                {{ selectedProgram[1] }}
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="program-select" id='programs-list'>
                <li ng-repeat="program in programs" role="presentation">
                    <a role="menuitem" tabindex="-1" href="#" ng-click="programSelected(program)">{{ program[1] }}</a>
                </li>
            </ul>
        </span>
        
        <div class="panel panel-default" style='margin-top: 20px'>
            <table class='table table-hover' id='elective-statistics-table'>
                <thead>
                    <tr>
                        <th style='width: 50px'>#</th>
                        <th style='width: 150px'>Course number</th>
                        <th>Course name</th>
                        <th class='center-text'>Count</th>
                        <th class='center-text'>Preapprove</th>
                    </tr>
                </thead>
                
                <tbody>
                    <tr ng-repeat="elective in electives | limitTo:numElectivesToShow">
                        <th scope="row">{{ $index + 1 }}</th>
                        <td>{{ elective.course_number }}</td>
                        <td>{{ elective.course_name }}</td>
                        <td class='center-text'>{{ elective.freq }}</td>
                        <td class='center-text'>
                            <button ng-show="elective.preapproved == 0" class="btn btn-success btn-xs"
                                ng-click="preapprove(elective)" type="button">Add</button>
                            <button ng-show="elective.preapproved == 1" class="btn btn-danger btn-xs"
                                ng-click="removePreapproval(elective)" type="button">Remove</button>
                        </td>
                    </tr>
                    
                    <tr ng-show="!electives.length">
                        <th></th>
                        <td><i>No courses found</i></td>
                    </tr>
                </tbody>
            </table>
        </div>
        
    </div>
</div>