<div ng-controller="StatisticsController" class="row" style='width: 90%; min-height: calc(100% - 55px); padding-bottom: 20px; margin-left: auto; margin-right: auto'>
    <div class="col-sm-12" style='height: 100%'>
        View top <input id='count-input' class='form-control' style='width:60px; display:inline !important' ng-model="numElectivesToShow" /> approved elective requests from <span class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="program-select" data-toggle="dropdown" aria-expanded="true">
            {{ selectedProgram[1] }}
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="program-select" id='programs-list'>
            <li ng-repeat="program in programs" role="presentation">
              <a role="menuitem" tabindex="-1" href="#" ng-click="programSelected(program)">{{ program[1] }}</a>
            </li>
          </ul>
        </span>
        <table class='table'>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Course number</th>
                    <th>Course name</th>
                    <th>Count</th>
                    <th>Add to Preapproved List</th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="elective in electives | limitTo:numElectivesToShow">
                    <td>{{ $index + 1 }}</td>
                    <td>{{ elective.course_number }}</td>
                    <td>{{ elective.course_name }}</td>
                    <td>{{ elective.freq }}</td>
                    <td><span class='glyphicon glyphicon-plus-sign' style='font-size: 1.4em; color: blue'></span></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>