<div class="col-sm-6" id='user-editor'>
    <div id='requirements-storage' style='display: none'><?= Zend_Json::encode($this->requirements) ?></div>

    <ul class="nav nav-tabs">
        <li id='user-info-tab' class='active'>
            <a class="dropdown-toggle" href="#user-info-pane" data-toggle="tab">User Info</a>
        </li>
        
        <li id='courses-tab' class='' style='display: none'>
            <a class="dropdown-toggle" href="#courses-pane" data-toggle="tab">Courses&nbsp;&nbsp;<span class="badge">5</span></a>
        </li>
    </ul>
    
    <div class="tab-content">
        <div id="user-info-pane" class="tab-pane in active">
            <div id='not-activated-notice' class="alert alert-block alert-info" style='display: none; margin-top: 10px'>
                <h4 class="alert-heading">User account not activated</h4>
                This user has never logged in to EASy. This account will be activated after s/he logs in and creates a new password.
            </div>
            
            <form class="form-horizontal" role="form" target='iframe-dummy' id='user-info-form' action="<?= $this->baseUrl(); ?>/users/create" method="post" style='margin-top: 10px'>
                <input type="hidden" ng-model='currentProgram' name='type' value='<?= $this->type ?>'>
                <input type='hidden' name='from' value='<?= Zend_Controller_Front::getInstance()->getRequest()->getRequestUri(); ?>'>

                <div class="form-group">
                    <label class="col-lg-3 control-label">Andrew ID</label>
                    <div class="col-lg-9">
                        <input type="text" name='andrew-id' class="form-control">
                        <!-- Temporary compatibility solution: change this value to trigger loading courses in Angular -->
                        <input id='andrew-id-to-load-courses' ng-model='currentStudent.andrewId' ng-change='loadCurrentStudentCourses()' style='display: none'>
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="col-lg-3 control-label">Name</label>
                    <div class="col-lg-8">
                        <input type="text" ng-model='currentStudent.name' name='name' class="form-control">
                    </div>
                    <div class='col-lg-1' style='padding-left: 0px; margin-left: -10px'>
                        <button type="button" id='btn-infer-name' onclick='infer("name")' class="btn btn-default">
                            <i class="fa fa-book"></i>
                        </button>
                    </div>
                </div>
                
            <?php if ($this->type != 'admin') { ?>                
                <div class="form-group">
                    <label class="col-lg-3 control-label">Primary Major</label>
                    <div class="col-lg-8">
                        <input type="text" name='major' class="form-control">
                    </div>
                    <div class='col-lg-1' style='padding-left: 0px; margin-left: -10px'>
                        <button type="button" id='btn-infer-major' onclick='infer("major")' class="btn btn-default">
                            <i class="fa fa-book"></i>
                        </button>
                    </div>
                </div>
  
                <div class="form-group">
                    <label class="col-lg-3 control-label">Enrolled</label>
                    <div class="col-lg-2">
                        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                            {{ seasons[selectedEnrolledSeason] }}
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li ng-repeat='season in seasons'>
                                <a role="menuitem" tabindex="-1" href="javascript: ;" value='{{ $index }}' ng-click='selectEnrollSeason($index)'>{{ season }}</a>
                            </li>
                        </ul>
                        <!-- NOTE: a temporary way to communicate between angular and non-angular code. Remove after fully converted -->
                        <input id='enroll-season' name='enroll-season' ng-model='selectedEnrolledSeason' style='display: none'>
                    </div>
                    <div class='col-lg-7'>
                        <input id='enroll-year' type="number" name='enroll-year' class="form-control" placeholder='Year'>
                    </div>
                </div>
            
                <div class="form-group">
                    <label class="col-lg-3 control-label">Graduation</label>
                    <div class="col-lg-2">
                        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                            {{ seasons[selectedGraduationSeason] }}
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li ng-repeat='season in seasons'>
                                <a role="menuitem" tabindex="-1" href="javascript: ;" value='{{ $index }}' ng-click='selectGraduationSeason($index)'>{{ season }}</a>
                            </li>
                        </ul>
                        <!-- NOTE: a temporary way to communicate between angular and non-angular code. Remove after fully converted -->
                        <input id='graduation-season' name='graduation-season' ng-model='selectedGraduationSeason' style='display: none'>
                    </div>
                    <div class='col-lg-7'>
                        <input id='graduation-year' type="number" name='graduation-year' class="form-control" placeholder='Year'>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-3 control-label">Status</label>
                    <span class="btn-group col-lg-9" data-toggle="buttons">
                        <label class="btn btn-default active">
                            <input type="radio" name="status" value="enrolled">Enrolled
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="status" value="graduated">Graduated
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="status" value="inactive">Inactive
                        </label>
                    </span>
                </div>

                <div class="form-group">
                    <label class="col-lg-3 control-label">FT/PT Status</label>
                    <span class="btn-group col-lg-9" data-toggle="buttons">
                        <label class="btn btn-default active">
                            <input type="radio" name="is-full-time" value="1">Full-time
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="is-full-time" value="0">Part-time
                        </label>
                    </span>
                </div>
            
            <?php } else { ?>
                Receive elective requests and questions from students in
                <span class="input-group">
                    <span class="input-group-addon" id='receive-from-mhci'>
                        <input type="checkbox" name='receive-from-mhci'>
                    </span>
                    <label class="form-control">MHCI</label>
                </span>
                <span class="input-group">
                    <span class="input-group-addon" id='receive-from-metals'>
                        <input type="checkbox" name='receive-from-metals'>
                    </span>
                    <label class="form-control">METALS</label>
                </span>
                <span class="input-group">
                    <span class="input-group-addon" id='receive-from-bhci'>
                        <input type="checkbox" name='receive-from-bhci'>
                    </span>
                    <label class="form-control">BHCI</label>
                </span>
                <span class="input-group">
                    <span class="input-group-addon" id='receive-from-ugminor'>
                        <input type="checkbox" name='receive-from-ugminor'>
                    </span>
                    <label class="form-control">Undergraduate Minor</label>
                </span>
                <span class="input-group">
                    <span class="input-group-addon" id='receive-from-learning-media'>
                        <input type="checkbox" name='receive-from-learning-media'>
                    </span>
                    <label class="form-control">Learning Media Minor</label>
                </span>
            <?php } ?>
                
            <textarea rows='3' name='notes' class="form-control" placeholder="Notes" style='margin-bottom: 20px'></textarea>
            
            <button type="button" onclick='clearUserInfoFields()' class="btn btn-warning" style='margin-right:10px'>Clear All Fields</button>
            <button type="button" id='submit-new-user' class="btn btn-primary" style='margin-right: 5px'>Add or Update</button> <span id='span-after-add'>as <b><?php 
                                                if ($this->type == 'mhci') echo("MHCI");
                                                else if ($this->type == 'metals') echo('METALS');
                                                else if ($this->type == 'bhci') echo("BHCI");
                                                else if ($this->type == 'ugminor') echo("Undergraduate Minor");
                                                else if ($this->type == 'learning-media') echo("Learning Media Minor");
                                                else if ($this->type == 'admin') echo("Administrator") ?></b>
            <span id='new-user-email-notice' style='margin-left: 10px' class="glyphicon glyphicon-question-sign"></span></span>
            <button type="button" id='delete-user' class="btn btn-danger pull-right" style='display: none'>Delete</button>
            </form>
        </div>
        <div id="courses-pane" class="tab-pane">

            <div class="panel panel-default" id='panel-cores' style='margin-top: 20px'>
                <div class="panel-heading bold" style='font-size: 15px'>Core requirements<h6 id='core-grade-req' class='grade-req'></h6></div>
                <div class="row main-row">
                    <div class="col-sm-12">
                        <h5 class='no-courses' style='display: none'></h5>
                        <table id='table-cores' class='table table-hover'>
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Course name</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!-- Learning media minor does not have prereqs/place-outs -->
            <?php if ($this->type != 'learning-media') { ?>

                <div class="panel panel-default" id='panel-<?= ($this->type == "mhci" || $this->type == "metals") ? "place-outs" : "prereqs" ?>'>
                    <div class="panel-heading bold" style='font-size: 15px'><?php 
                        if ($this->type == "mhci" || $this->type == "metals") {
                            echo "Place-out courses";
                        } else {
                            echo "Prerequisites";
                        ?><h6 id='prerequisite-grade-req' class='grade-req'></h6><?php
                        }
                    ?></div>
                    <div class="row main-row">
                        <div class="col-sm-12">
                            <h5 class='no-courses' style='display: none'></h5>
                            <table class='table table-hover'>
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Course name</th>
                                        <th>Status</th>
                                        <?php if ($this->type == 'mhci' || $this->type == 'metals') { ?><th>Notes</th><?php } ?>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div id='panel-electives' class="panel panel-default" style='margin-top: 20px'>
                    <div class="panel-heading bold" style='font-size: 15px'>Electives<h6 id='elective-grade-req' class='grade-req'></h6></div>
                    <div class="panel-body">
                        <div class="row main-row">
                            <div id='summary-electives' class="col-sm-12">
                                
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>

            <!-- Using MessageCtrl in AngularJS -->
            <div class="panel panel-default" style='margin-top: 20px' ng-controller='MessageCtrl'>
                <div class="panel-heading bold" style='font-size: 15px'>All courses</div>
                <div class="panel-body">
                    <div class="row main-row">
                        <div class="col-sm-12">
                            <h4 ng-hide='showCoursesList'>No courses to show.</h4>
                            <table ng-show='showCoursesList' class='table table-hover'>
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Number</th>
                                        <th>Units</th>
                                        <th>Type</th>
                                        <th>Grade</th>
                                        <th>Status</th>
                                        <th>Messages</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat='course in currentStudent.courses' ng-if='course.taking_as != "place-out"'
                                        data-toggle='modal' data-target='#course-details' ng-click='courseSelected(course)'>
                                        <td>{{ $index + 1 }}</td>
                                        <td>{{ course.course_name == '' ? '-' : course.course_name }}</td>
                                        <td>{{ course.course_number }}</td>
                                        <td>{{ course.units == 0 ? '-' : course.units }}</td>
                                        <td>{{ takingAs2Text[course.taking_as] }}</td>
                                        <td>{{ (course.grade == null || course.grade == '' || course.grade == 'na') ? '-' : grade2Text[course.grade] }}</td>
                                        <!-- TODO May want to create a template and reuse this -->
                                        <td>
                                            <span ng-show='course.status == "need-clarification"' class='text-warning'>
                                                {{ status2Text[course.status] }}
                                            </span>
                                            <span ng-show='course.status == "submitted"' class='text-danger'>
                                                {{ status2Text[course.status] }}
                                            </span>
                                            <span ng-show='course.status == "approved"' class='text-success'>
                                                {{ status2Text[course.status] }}
                                            </span>
                                            <span ng-show='course.status != "need-clarification" && course.status != "submitted" && course.status != "approved"'>
                                                {{ status2Text[course.status] }}
                                            </span>
                                        </td>
                                        <td>
                                            <a ng-click='showMessages(course.id); $event.stopPropagation();' class='{{ course.has_unread_msg ? "text-danger" : "" }}' courseid='{{ course.id }}' href='javascript: ;'>
                                                {{ course.has_unread_msg ? 'Unread' : 'View' }}
                                            </a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>

                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-add-course" ng-click='resetNewCourse()'>Add Course</button>
                            <div id='div-ordering' ng-show='showCoursesList' class='pull-right'>
                                <span style='margin-right: 5px'>Sort by</span>
                                <span class="btn-group" data-toggle="buttons">
                                    <label ng-repeat='(method, methodText) in courseSortingMethods'
                                        ng-click='courseSortingMethodSelected(method)'
                                        class='btn btn-default {{ courseSortingMethod == method ? "active" : "" }}'>
                                        <input type='radio'>{{ methodText }}
                                    </label>
                                </span>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>

            <div class="row main-row">
                <div class="col-sm-12">
                    <div style='margin-left: 10px; font-weight: bold'>Notes</div>
                    <textarea rows='3' name='notes' id='courses-pane-notes' class="form-control" placeholder="Notes" style='margin-top: 5px'></textarea>
                </div>
            </div>
        </div>
    </div>
</div>