<div class="col-sm-6" id='user-editor'>
    <div id='requirements-storage' style='display: none'><?= Zend_Json::encode($this->requirements) ?></div>

    <ul class="nav nav-tabs">
        <li id='user-info-tab' class='active'>
            <a class="dropdown-toggle" href="#user-info-pane" data-toggle="tab">User Info</a>
        </li>
        
        <li id='courses-tab' class='' style='display: none'>
            <a class="dropdown-toggle" href="#courses-pane" data-toggle="tab">Courses&nbsp;&nbsp;<span class="badge">5</span></a>
        </li>
    </ul>
    
    <div class="tab-content">
        <div id="user-info-pane" class="tab-pane in active">
            <div id='not-activated-notice' class="alert alert-block alert-info" style='display: none; margin-top: 10px'>
                <h4 class="alert-heading">User account not activated</h4>
                This user has never logged in to EASy. This account will be activated after s/he logs in and creates a new password.
            </div>
            
            <form target='iframe-dummy' id='user-info-form' action="<?= $this->baseUrl(); ?>/users/create" method="post" style='margin-top: 10px'>
                <input type="hidden" name='type' value='<?= $this->type ?>'>
                <input type='hidden' name='from' value='<?= Zend_Controller_Front::getInstance()->getRequest()->getRequestUri(); ?>'>
            <?php if ($this->type != 'admin') { ?>
                <span class="input-group">
                    <span class="input-group-addon">Andrew ID</span>
                    <input type="text" name='andrew-id' class="form-control">
                </span>
                
                <span class="input-group" style='display: inline-table; width: calc(100% - 50px)'>
                    <span class="input-group-addon">Name</span>
                    <input type="text" name='name' class="form-control">                        
                </span>

                <button type="button" id='btn-infer-name' onclick='infer("name")' class="btn btn-default"><i class="fa fa-book"></i></button>
                
                <span class="input-group" style='display: inline-table; width: calc(100% - 50px)'>
                    <span class="input-group-addon">Primary Major</span>
                    <input type="text" name='major' class="form-control">
                </span>

                <button type="button" id='btn-infer-major' onclick='infer("major")' class="btn btn-default"><i class="fa fa-book"></i></button>
            
                <div class="input-group">
                    <span class="input-group-addon">Entered Program</span>
                    <input id='enroll-date' style='background-color: white' readonly type="text" name='enroll-date' class="form-control">
                </div>
            
                <div class="input-group">
                    <span class="input-group-addon">Expected Graduation</span>
                    <input id='graduation-date' style='background-color: white' readonly type="text" name='graduation-date' class="form-control">
                </div>

                <div class="input-group">
                    <span class="input-group-addon">Status</span>
                    <span class="btn-group" data-toggle="buttons">
                        <label class="btn btn-default active" style='border-top-left-radius: 0; border-bottom-left-radius: 0'>
                            <input type="radio" name="status" value="enrolled">Enrolled
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="status" value="graduated">Graduated
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="status" value="inactive">Inactive
                        </label>
                    </span>
                </div>

                <div class="input-group">
                    <span class="input-group-addon">FT/PT Status</span>
                    <span class="btn-group" data-toggle="buttons">
                        <label class="btn btn-default active" style='border-top-left-radius: 0; border-bottom-left-radius: 0'>
                            <input type="radio" name="is-full-time" value="1">Full-time
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="is-full-time" value="0">Part-time
                        </label>
                    </span>
                </div>
            
            <?php } else { ?>
                <div class="input-group">
                    <span class="input-group-addon">Andrew ID</span>
                    <input type="text" name='andrew-id' class="form-control">
                </div>
                
                <div class="input-group">
                    <span class="input-group-addon">Name</span>
                    <input type="text" name='name' class="form-control">
                </div>

                Receive elective requests and questions from students in
                <span class="input-group">
                    <span class="input-group-addon" id='receive-from-mhci'>
                        <input type="checkbox" name='receive-from-mhci'>
                    </span>
                    <label class="form-control">MHCI</label>
                </span>
                <span class="input-group">
                    <span class="input-group-addon" id='receive-from-metals'>
                        <input type="checkbox" name='receive-from-metals'>
                    </span>
                    <label class="form-control">METALS</label>
                </span>
                <span class="input-group">
                    <span class="input-group-addon" id='receive-from-bhci'>
                        <input type="checkbox" name='receive-from-bhci'>
                    </span>
                    <label class="form-control">BHCI</label>
                </span>
                <span class="input-group">
                    <span class="input-group-addon" id='receive-from-ugminor'>
                        <input type="checkbox" name='receive-from-ugminor'>
                    </span>
                    <label class="form-control">Undergraduate Minor</label>
                </span>
            <?php } ?>
                
            <textarea rows='3' name='notes' class="form-control" placeholder="Notes" style='margin-bottom: 20px'></textarea>
            
            <button type="button" onclick='clearUserInfoFields()' class="btn btn-warning" style='margin-right:10px'>Clear All Fields</button>
            <button type="button" id='submit-new-user' class="btn btn-primary" style='margin-right: 5px'>Add or Update</button> <span id='span-after-add'>as <b><?php 
                                                if ($this->type == 'mhci') echo("MHCI");
                                                else if ($this->type == 'metals') echo('METALS');
                                                else if ($this->type == 'bhci') echo("BHCI");
                                                else if ($this->type == 'ugminor') echo("Undergraduate Minor");
                                                else if ($this->type == 'admin') echo("Administrator") ?></b>
            <span id='new-user-email-notice' style='margin-left: 10px' class="glyphicon glyphicon-question-sign"></span></span>
            <button type="button" id='delete-user' class="btn btn-danger pull-right" style='display: none'>Delete</button>
            </form>
        </div>
        <div id="courses-pane" class="tab-pane">

            <div class="panel panel-default" id='panel-cores' style='margin-top: 20px'>
                <div class="panel-heading bold" style='font-size: 15px'>Core requirements<h6 id='core-grade-req' class='grade-req'></h6></div>
                <div class="row main-row">
                    <div class="col-sm-12">
                        <h5 class='no-courses' style='display: none'></h5>
                        <table id='table-cores' class='table'>
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Course name</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="panel panel-default" id='panel-<?= ($this->type == "mhci" || $this->type == "metals") ? "place-outs" : "prereqs" ?>'>
                <div class="panel-heading bold" style='font-size: 15px'><?php 
                    if ($this->type == "mhci" || $this->type == "metals") {
                        echo "Place-out courses";
                    } else {
                        echo "Prerequisites";
                    ?><h6 id='prerequisite-grade-req' class='grade-req'></h6><?php
                    }
                ?></div>
                <div class="row main-row">
                    <div class="col-sm-12">
                        <h5 class='no-courses' style='display: none'></h5>
                        <table class='table table-hover'>
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Course name</th>
                                    <th>Status</th>
                                    <?php if ($this->type == 'mhci' || $this->type == 'metals') { ?><th>Notes</th><?php } ?>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div id='panel-electives' class="panel panel-default" style='margin-top: 20px'>
                <div class="panel-heading bold" style='font-size: 15px'>Electives<h6 id='elective-grade-req' class='grade-req'></h6></div>
                <div class="panel-body">
                    <div class="row main-row">
                        <div id='summary-electives' class="col-sm-12">
                            
                        </div>
                    </div>
                </div>
            </div>

            <!-- Using MessageCtrl in AngularJS -->
            <div class="panel panel-default" style='margin-top: 20px' ng-controller='MessageCtrl'>
                <div class="panel-heading bold" style='font-size: 15px'>All courses</div>
                <div class="panel-body">
                    <div class="row main-row" id='row-electives-placeouts'>
                        <div class="col-sm-12">
                            <h4 id='no-courses' style='display: none'>No courses to show.</h4>
                            <table id='table-courses' class='table table-hover'>
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Number</th>
                                        <th>Units</th>
                                        <th>Type</th>
                                        <th>Grade</th>
                                        <th>Status</th>
                                        <th>Messages</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>

                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-add-course">Add Course</button>
                            <div id='div-ordering' class='pull-right'>
                                <span style='margin-right: 5px'>Sort by</span>
                                <span class="btn-group" data-toggle="buttons">
                                    <label class="btn btn-default active" id='order-by-time'>
                                        <input type="radio">Submission time
                                    </label>
                                    <label class="btn btn-default" id='order-by-status'>
                                        <input type="radio">Status
                                    </label>
                                </span>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>

            <div class="row main-row">
                <div class="col-sm-12">
                    <div style='margin-left: 10px; font-weight: bold'>Notes</div>
                    <textarea rows='3' name='notes' id='courses-pane-notes' class="form-control" placeholder="Notes" style='margin-top: 5px'></textarea>
                </div>
            </div>
        </div>
    </div>
</div>