<iframe name='iframe-dummy' src="" style='display: none'>
</iframe>

<div class="row" style='width: 90%; min-height: calc(100% - 55px); padding-bottom: 20px; margin-left: auto; margin-right: auto'>
    <div class="col-sm-6" style='height: 100%'>
        <ul class="nav nav-tabs">
            <li class='<?= ($this->type == "mhci" ? "active" : "") ?>'>
                <a class="dropdown-toggle" href="<?= $this->baseUrl(); ?>/admin/usrmgr/type/mhci">MHCI</a>
            </li>

            <li class='<?= ($this->type == "metals" ? "active" : "") ?>'>
                <a class="dropdown-toggle" href="<?= $this->baseUrl(); ?>/admin/usrmgr/type/metals">METALS</a>
            </li>
            
            <li class='<?= ($this->type == "bhci" ? "active" : "") ?>'>
                <a class="dropdown-toggle" href="<?= $this->baseUrl(); ?>/admin/usrmgr/type/bhci">BHCI</a>
            </li>
            
            <li class='<?= ($this->type == "ugminor" ? "active" : "") ?>'>
                <a class="dropdown-toggle" href="<?= $this->baseUrl(); ?>/admin/usrmgr/type/ugminor">Undergraduate Minor</a>
            </li>
            
            <li class='<?= ($this->type == "admin" ? "active" : "") ?>'>
                <a class="dropdown-toggle" href="<?= $this->baseUrl(); ?>/admin/usrmgr/type/admin">Administrators</a>
            </li>
        </ul>
        
        <div style='overflow: auto; max-height:80%'>

            <?php if ($this->type != "admin") { ?>
            <input id='search-student' style='margin-top: 20px' placeholder='Enter name or Andrew ID to filter' type="text" class="form-control">
            <?php } ?>

            <table id='users-table' class="table table-hover table-striped <?php if ($this->type == 'admin') echo 'admin-table';?>">
                <thead>
                    <tr>
                        <?php if ($this->type == 'admin') { ?>
                        <th>Andrew ID</th>
                        <th>Name</th>
                        <?php } else { ?>
                        <th>Andrew ID</th>
                        <th>Name</th>
                        <th>Date entered program</th>
                        <th>Graduation date</th>
                        <th>&nbsp;</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
        
        <h4 id='no-users' style='display: none; text-align: center'>No users to show.</h4>
        <h4 id='loading-users' style='display: none; text-align: center'>Loading users list...</h4>

        <?php if ($this->type != "admin") { ?>
            <div class="panel panel-default" id='panel-filter' style='margin-top: 20px'>
                <div class="panel-heading bold" style='font-size: 15px'>Filter</div>
                <div class="row main-row" style='padding-bottom: 20px; padding-top: 10px'>
                    <div class="col-sm-12">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" checked id='show-enrolled'> Show enrolled students
                            </label>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id='show-graduated'> Show graduated and inactive students
                            </label>
                        </div>
                        Show students entered program between
                        <span style='display: inline-block; width: 100px'>
                            <input id='filter-year-lower-bound' style='background-color: white; height: 30px' readonly type="text" class="form-control">
                        </span>
                         and 
                        <span style='display: inline-block; width: 100px'>
                            <input id='filter-year-upper-bound' style='background-color: white; height: 30px' readonly type="text" class="form-control">
                        </span>

                        <div style='margin-top: 10px'>
                            <button type="button" id='btn-clear-filter' class="btn btn-default" onclick='clearFilter()'>Clear Filter</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default" id='panel-import' style='margin-top: 20px'>
                <div class="panel-heading bold" style='font-size: 15px'>Import</div>
                <div class="row main-row" style='padding-bottom: 20px; padding-top: 20px'>
                    <div class="col-sm-12">
                        <button type="button" id='btn-import-users' class="btn btn-default" data-toggle="modal" data-target="#modal-import-users">Import Users</button>
                    </div>
                </div>
            </div>
        <?php } ?>
        
    </div>

    <div class="col-sm-6" id='user-editor'>
        <div id='requirements-storage' style='display: none'><?= Zend_Json::encode($this->requirements) ?></div>

        <ul class="nav nav-tabs">
            <li id='user-info-tab' class='active'>
                <a class="dropdown-toggle" href="#user-info-pane" data-toggle="tab">User Info</a>
            </li>
            
            <li id='courses-tab' class='' style='display: none'>
                <a class="dropdown-toggle" href="#courses-pane" data-toggle="tab">Courses&nbsp;&nbsp;<span class="badge">5</span></a>
            </li>
        </ul>
        
        <div class="tab-content">
            <div id="user-info-pane" class="tab-pane in active">
                <div id='not-activated-notice' class="alert alert-block alert-info" style='display: none; margin-top: 10px'>
                    <h4 class="alert-heading">User account not activated</h4>
                    This user has never logged in to EASy. This account will be activated after s/he logs in and creates a new password.
                </div>
                
                <form target='iframe-dummy' id='user-info-form' action="<?= $this->baseUrl(); ?>/users/create" method="post" style='margin-top: 10px'>
                    <input type="hidden" name='type' value='<?= $this->type ?>'>
                    <input type='hidden' name='from' value='<?= Zend_Controller_Front::getInstance()->getRequest()->getRequestUri(); ?>'>
                <?php if ($this->type != 'admin') { ?>
                    <span class="input-group">
                        <span class="input-group-addon">Andrew ID</span>
                        <input type="text" name='andrew-id' class="form-control">
                    </span>
                    
                    <span class="input-group" style='display: inline-table; width: calc(100% - 50px)'>
                        <span class="input-group-addon">Name</span>
                        <input type="text" name='name' class="form-control">                        
                    </span>

                    <button type="button" id='btn-infer-name' onclick='infer("name")' class="btn btn-default"><i class="fa fa-book"></i></button>
                    
                    <span class="input-group" style='display: inline-table; width: calc(100% - 50px)'>
                        <span class="input-group-addon">Primary Major</span>
                        <input type="text" name='major' class="form-control">
                    </span>

                    <button type="button" id='btn-infer-major' onclick='infer("major")' class="btn btn-default"><i class="fa fa-book"></i></button>
                
                    <div class="input-group">
                        <span class="input-group-addon">Entered Program</span>
                        <input id='enroll-date' style='background-color: white' readonly type="text" name='enroll-date' class="form-control">
                    </div>
                
                    <div class="input-group">
                        <span class="input-group-addon">Expected Graduation</span>
                        <input id='graduation-date' style='background-color: white' readonly type="text" name='graduation-date' class="form-control">
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon">Status</span>
                        <span class="btn-group" data-toggle="buttons">
                            <label class="btn btn-default active" style='border-top-left-radius: 0; border-bottom-left-radius: 0'>
                                <input type="radio" name="status" value="enrolled">Enrolled
                            </label>
                            <label class="btn btn-default">
                                <input type="radio" name="status" value="graduated">Graduated
                            </label>
                            <label class="btn btn-default">
                                <input type="radio" name="status" value="inactive">Inactive
                            </label>
                        </span>
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon">FT/PT Status</span>
                        <span class="btn-group" data-toggle="buttons">
                            <label class="btn btn-default active" style='border-top-left-radius: 0; border-bottom-left-radius: 0'>
                                <input type="radio" name="is-full-time" value="1">Full-time
                            </label>
                            <label class="btn btn-default">
                                <input type="radio" name="is-full-time" value="0">Part-time
                            </label>
                        </span>
                    </div>
                
                <?php } else { ?>
                    <div class="input-group">
                        <span class="input-group-addon">Andrew ID</span>
                        <input type="text" name='andrew-id' class="form-control">
                    </div>
                    
                    <div class="input-group">
                        <span class="input-group-addon">Name</span>
                        <input type="text" name='name' class="form-control">
                    </div>

                    Receive elective requests and questions from students in
                    <span class="input-group">
                        <span class="input-group-addon" id='receive-from-mhci'>
                            <input type="checkbox" name='receive-from-mhci'>
                        </span>
                        <label class="form-control">MHCI</label>
                    </span>
                    <span class="input-group">
                        <span class="input-group-addon" id='receive-from-metals'>
                            <input type="checkbox" name='receive-from-metals'>
                        </span>
                        <label class="form-control">METALS</label>
                    </span>
                    <span class="input-group">
                        <span class="input-group-addon" id='receive-from-bhci'>
                            <input type="checkbox" name='receive-from-bhci'>
                        </span>
                        <label class="form-control">BHCI</label>
                    </span>
                    <span class="input-group">
                        <span class="input-group-addon" id='receive-from-ugminor'>
                            <input type="checkbox" name='receive-from-ugminor'>
                        </span>
                        <label class="form-control">Undergraduate Minor</label>
                    </span>
                <?php } ?>
                    
                <textarea rows='3' name='notes' class="form-control" placeholder="Notes" style='margin-bottom: 20px'></textarea>
                
                <button type="button" onclick='clearUserInfoFields()' class="btn btn-warning" style='margin-right:10px'>Clear All Fields</button>
                <button type="button" id='submit-new-user' class="btn btn-primary" style='margin-right: 5px'>Add or Update</button> <span id='span-after-add'>as <b><?php 
                                                    if ($this->type == 'mhci') echo("MHCI");
                                                    else if ($this->type == 'metals') echo('METALS');
                                                    else if ($this->type == 'bhci') echo("BHCI");
                                                    else if ($this->type == 'ugminor') echo("Undergraduate Minor");
                                                    else if ($this->type == 'admin') echo("Administrator") ?></b>
                <span id='new-user-email-notice' style='margin-left: 10px' class="glyphicon glyphicon-question-sign"></span></span>
                <button type="button" id='delete-user' class="btn btn-danger pull-right" style='display: none'>Delete</button>
                </form>
            </div>
            <div id="courses-pane" class="tab-pane">

                <div class="panel panel-default" id='panel-cores' style='margin-top: 20px'>
                    <div class="panel-heading bold" style='font-size: 15px'>Core requirements<h6 style='float: right; color: gray'>(B or above required)</h6></div>
                    <div class="row main-row">
                        <div class="col-sm-12">
                            <h5 class='no-courses' style='display: none'></h5>
                            <table id='table-cores' class='table'>
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Course name</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default" id='panel-<?= ($this->type == "mhci" || $this->type == "metals") ? "place-outs" : "prereqs" ?>'>
                    <div class="panel-heading bold" style='font-size: 15px'><?= 
                        ($this->type == "mhci" || $this->type == "metals") ? "Place-out courses" : "Prerequisites"
                    ?></div>
                    <div class="row main-row">
                        <div class="col-sm-12">
                            <h5 class='no-courses' style='display: none'></h5>
                            <table class='table table-hover'>
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Course name</th>
                                        <th>Status</th>
                                        <?php if ($this->type == 'mhci' || $this->type == 'metals') { ?><th>Notes</th><?php } ?>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div id='panel-electives' class="panel panel-default" style='margin-top: 20px'>
                    <div class="panel-heading bold" style='font-size: 15px'>Electives<h6 style='float: right; color: gray'>(C or above required)</h6></div>
                    <div class="panel-body">
                        <div class="row main-row">
                            <div id='summary-electives' class="col-sm-12">
                                
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default" style='margin-top: 20px'>
                    <div class="panel-heading bold" style='font-size: 15px'>All courses</div>
                    <div class="panel-body">
                        <div class="row main-row" id='row-electives-placeouts'>
                            <div class="col-sm-12">
                                <h4 id='no-courses' style='display: none'>No courses to show.</h4>
                                <table id='table-courses' class='table table-hover'>
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Course name</th>
                                            <th>Course No.</th>
                                            <th>Type</th>
					    <th>Grade</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>

                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-add-course">Add Course</button>
                                <div id='div-ordering' class='pull-right'>
                                    <span style='margin-right: 5px'>Sort by</span>
                                    <span class="btn-group" data-toggle="buttons">
                                        <label class="btn btn-default active" id='order-by-time'>
                                            <input type="radio">Submission time
                                        </label>
                                        <label class="btn btn-default" id='order-by-status'>
                                            <input type="radio">Status
                                        </label>
                                    </span>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row main-row">
                    <div class="col-sm-12">
                        <div style='margin-left: 10px; font-weight: bold'>Notes</div>
                        <textarea rows='3' name='notes' id='courses-pane-notes' class="form-control" placeholder="Notes" style='margin-top: 5px'></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="prerequisite-details" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
    <div class="modal-dialog">
	<div class="modal-content">
            <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title" id="modalTitle">Prerequisite details</h4>
	    </div>
            <div class="modal-body" style='padding-bottom: 0px'>
		<div id='prerequisite-name' style='display: none'></div>
                <div class="input-group">
                    <span class="input-group-addon">Status</span>
                    <span class="btn-group" data-toggle="buttons">
                        <label class="btn btn-default active" style="border-top-left-radius: 0; border-bottom-left-radius: 0">
                            <input type="radio" name="prerequisite-status" value="satisfied">Set to "Satisfied"
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="prerequisite-status" value="not-satisfied">Set to "Not satisfied"
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="prerequisite-status" value="infer">Infer from courses
                        </label>
                    </span>
                </div>
            </div>
            <div class="modal-footer">
                <button id='prerequisite-update-status' type="button" class="btn btn-primary">Update Status</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="place-out-details" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modalTitle">Course details</h4>
            </div>
            <div class="modal-body" style='padding-bottom: 0px'>
                <div id='place-out-id' style='display: none'></div>
                <table class='table'>
                    <tr>
                        <td class='bold' style='width: 200px'>Student name</td>
                        <td id='modal-place-out-student-name'></td>
                    </tr>
                    <tr>
                        <td class='bold'>Andrew ID</td>
                        <td id='modal-place-out-andrew-id'></td>
                    </tr>
                    <tr>
                        <td class='bold'>Course name</td>
                        <td id='modal-place-out-name'></td>
                    </tr>
                    <tr>
                        <td class='bold'>Taking as</td>
                        <td>Place-out</td>
                    </tr>
                    <tr>
                        <td class='bold'>Status</td>
                        <td id='modal-place-out-status'>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Not satisfied</button>
                                <ul class="dropdown-menu" role="menu">
                                    <?= $this->produceList(['Satisfied', 'Not satisfied']) ?>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class='bold'>Notes</td>
                        <td id='modal-place-out-comment'>
                            <textarea style='resize: vertical' class='form-control' rows='3'></textarea>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <button id='place-out-update-status' type="button" class="btn btn-primary">Update Status</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="modal-import-users" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modalTitle">Import users</h4>
            </div>
            <form id='frm-file-upload' onsubmit='javascript: formSubmitted = 1;' target='iframe-import' method='post' action="<?= $this->baseUrl(); ?>/users/import" enctype="multipart/form-data">
                <div class="modal-body" style='padding-bottom: 0px'>
                    <div class="well">
                        The Excel file (*.xls, *.xlsx) should contain columns with the following headers (columns do not have to be in order):<br /><br />
                        <b>Program</b> (m = MHCI, metals = METALS, b = BHCI, minor = Undergraduate minor)<br />
                        <b>Andrew ID</b></br>
                        <b>Status</b> (e = Enrolled, g = Graduated, i = Inactive) (will default to Enrolled if no value specified)<br />
                        <b>FT/PT</b> (f = Full-time, p = Part-time) (will default to Full-time if no value specified)<br />
                        <b>Entered program</b> (format: MM/YYYY)<br />
                        <b>Expected graduation</b> (format: MM/YYYY)<br />
                        <br />
                        Optional columns:<br />
                        <b>Name</b></br>
                        <b>Primary major</b></br>
                        If these column is not present or the values are empty, EASy will attempt to retrieve data from CMU Directory. Retrieval failure may occur if CMU website is modified or updated.
                    </div>

                    <span class="input-group" style='<!-- width: 75%; display: inline-table -->'>
                        <span class="input-group-addon">File</span>
                        <input type="file" id='file' name='file' class="form-control" />
                    </span>

                    <script type="text/javascript">
                        formSubmitted = 0;
                        function checkImportResult() {
                            if (formSubmitted == 1) {
                                console.log($('iframe').contents().find('body').text());
                                var ret = $.parseJSON($('iframe').contents().find('body').text());
                                alert(ret['message']);
                                if (ret['success'] == 1) {
                                    location.reload();
                                }
                            }
                        }
                    </script>
                    <iframe style='display: none;' name="iframe-import" onload='checkImportResult()'></iframe>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button id='btn-upload-file' type="submit" class="btn btn-primary">Upload file</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal" id="course-details" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modalTitle">Course details</h4>
            </div>
            <div class="modal-body" style='padding-bottom: 0px'>
                <div id='dialog-course-id' style='display: none'></div>
                <table class='table'>
                    <tr>
                        <td class='bold' style='width: 200px'>Student name</td>
                        <td id='dialog-student-name'></td>
                    </tr>
                    <tr>
                        <td class='bold'>Andrew ID</td>
                        <td id='dialog-andrew-id'></td>
                    </tr>
                    <tr>
                        <td class='bold'>Course name</td>
                        <td id='dialog-course-name'></td>
                    </tr>
                    <tr>
                        <td class='bold'>Course number</td>
                        <td id='dialog-course-number'></td>
                    </tr>
                    <tr>
                        <td class='bold'>Units</td>
                        <td id='dialog-units'></td>
                    </tr>
                    <tr>
                        <td class='bold'>Description</td>
                        <td id='dialog-description'></td>
                    </tr>
                    <tr>
                        <td class='bold'>Taking as</td>
                        <td id='dialog-taking-as'></td>
                    </tr>
                    <tr>
                        <td class='bold'>Submission time</td>
                        <td id='dialog-submission-time'></td>
                    </tr>
                    <tr>
                        <td class='bold'>Status</td>
                        <td id='dialog-status'>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Awaiting Approval</button>
                                <ul class="dropdown-menu" role="menu"></ul>
                            </div>
                        </td>
                    </tr>
                    <tr id='tr-semester'>
                        <td class='bold'>Semester</td>
                        <td id='dialog-semester'>
                            <span id='dialog-semester-semester' class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Spring</button>
                                <ul class="dropdown-menu" role="menu">
                                    <?= $this->produceList(['Spring', 'Fall', 'Summer', 'N/A']) ?>
                                </ul>
                            </span>
                            <span id='dialog-semester-year' class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">2014</button>
                                <ul class="dropdown-menu" role="menu"></ul>
                            </span>
                        </td>
                    </tr>
                    <tr id='tr-grade'>
                        <td class='bold'>Grade</td>
                        <td id='dialog-grade'>
                            <span class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"></button>
                                <ul class="dropdown-menu" role="menu"></ul>
                            </span>
                        </td>
                    </tr>
                    <tr>
			<td class='bold'>Comment<br />(visible to student)</td>
                        <td id='dialog-comment'>
                            <textarea style='resize: vertical' class='form-control' rows='3'></textarea>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <button id='delete-course' type='button' class='btn btn-danger' style='float: left'>Delete Course</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button id='update-status' type="button" class="btn btn-primary">Update Status</button>
            </div>
        </div>
    </div>
</div>


<div class="modal" id="modal-add-course" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modalTitle">Add Course</h4>
            </div>
            <div class="modal-body" style='padding-bottom: 0px'>
                <table class='table'>
                    <tr>
                        <td class='bold'>Course name</td>
                        <td id='modal-add-course-name'>
                            <input class='form-control' />
                        </td>
                    </tr>
                    <tr>
                        <td class='bold'>Course number</td>
                        <td id='modal-add-course-number'>
                            <input class='form-control' />
                        </td>
                    </tr>
                    <tr>
                        <td class='bold'>Units</td>
                        <td id='modal-add-course-units'>
                            <input class='form-control' />
                        </td>
                    </tr>
                    <tr>
                        <td class='bold'>Taking as</td>
                        <td id='modal-add-course-type'>
                            <span class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Core</button>
                                <ul class="dropdown-menu" role="menu">
                                    <?php if ($this->type == "ugminor") { ?>
                                        <?= $this->produceList(['Elective', 'Prerequisite', 'Core']) ?>
                                    <?php } else if ($this->type == "bhci") { ?>
                                        <?= $this->produceList(['Restricted application elective', 'Free elective', 'Core', 'Prerequisite']) ?>
                                    <?php } else if ($this->type == "mhci" || $this->type == 'metals') { ?>
                                        <?= $this->produceList(['Elective', 'Core']) ?>
                                    <?php } ?>
                                </ul>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td class='bold'>Status</td>
                        <td id='modal-add-course-status'>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">In progress</button>
                                <ul class="dropdown-menu" role="menu"></ul>
                            </div>
                        </td>
                    </tr>
                    <tr id='tr-add-course-semester'>
                        <td class='bold'>Semester</td>
                        <td>
                            <span id='modal-add-course-semester' class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Spring</button>
                                <ul class="dropdown-menu" role="menu">
                                    <?= $this->produceList(['Spring', 'Fall', 'Summer', 'N/A']) ?>
                                </ul>
                            </span>
                            <span id='modal-add-course-year' class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">2014</button>
                                <ul class="dropdown-menu" role="menu"></ul>
                            </span>
                        </td>
                    </tr>
                    <tr id='tr-add-course-grade'>
                        <td class='bold'>Grade</td>
                        <td id='modal-add-course-grade'>
                            <span class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">N/A</button>
                                <ul class="dropdown-menu" role="menu"></ul>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td class='bold'>Comment</td>
                        <td id='modal-add-course-comment'>
                            <textarea style='resize: vertical' class='form-control' rows='3'></textarea>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button id='btn-add-course' type="button" class="btn btn-primary">Add</button>
            </div>
        </div>
    </div>
</div>